# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/toji_iiif',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/toji_iiif',
                'lib_path': 'toji_iiif'},
  'syms': { 'toji_iiif.core': { 'toji_iiif.core.TojiClient': ('core.html#tojiclient', 'toji_iiif/core.py'),
                                'toji_iiif.core.TojiClient.__init__': ('core.html#tojiclient.__init__', 'toji_iiif/core.py'),
                                'toji_iiif.core.TojiClient.createCanvases': ('core.html#tojiclient.createcanvases', 'toji_iiif/core.py'),
                                'toji_iiif.core.TojiClient.createCollection': ( 'core.html#tojiclient.createcollection',
                                                                                'toji_iiif/core.py'),
                                'toji_iiif.core.TojiClient.createManifest': ('core.html#tojiclient.createmanifest', 'toji_iiif/core.py'),
                                'toji_iiif.core.TojiClient.create_index': ('core.html#tojiclient.create_index', 'toji_iiif/core.py'),
                                'toji_iiif.core.TojiClient.main': ('core.html#tojiclient.main', 'toji_iiif/core.py')}}}
